/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2025 Marcelo "Ataxexe" Guimarães
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package com.backpackcloud.configuration;

import java.util.function.Supplier;
import java.util.stream.Stream;

/// A class that encapsulates a common logic found deepest in the legends of the
/// ancient pieces of voltage that formed the army of the digital century.
///
/// No, this wasn't generated by AI.
///
/// Anyway, when configuring an application, there is always a priority list with
/// places to search for the configuration file.
///
/// This class provides an opinionated priority list, together with a convention
/// for naming the locations. All based on analysis of the digital forges used
/// by both Elves and Dwarfs for multiple centuries.
///
/// The conventions used by this class, in the priority order are:
///
/// - File located at `env {NAME}_CONFIG_FILE`
/// - File located at `WORK_DIR/{name}.yml`
/// - File located at `USER_HOME/{name}.yml`
/// - Resource located at `META-INF/{name}.yml`
///
/// Where `{name}` is the variable part that is given for each instance of this class.
///
/// Before you start throwing your left arm, remember: this is an opinionated thing.
///
/// @author Ataxexe
public class ConfigurationSupplier implements Supplier<Configuration> {

  /// Holds the name that will be used as a convention
  private final String name;

  /// Creates a new Configuration Supplier using the given name to be used
  /// in the conventions.
  ///
  /// @param name the name to be used as part of the conventions.
  public ConfigurationSupplier(String name) {
    this.name = name;
  }

  public Configuration get() {
    return Stream.of(fromEnvironment(),
        fromWorkingDir(),
        fromUserHome())
      .filter(Configuration::isSet)
      .findFirst()
      .orElseGet(this::getDefault);
  }

  public Configuration fromEnvironment() {
    String path = System.getenv(name.toUpperCase() + "_CONFIG_FILE");
    return path != null ? new FileConfiguration(path) : Configuration.NOT_SUPPLIED;
  }

  public Configuration fromWorkingDir() {
    return new FileConfiguration("./" + name + ".yml");
  }

  public Configuration fromUserHome() {
    return new FileConfiguration(System.getProperty("user.home") + "/" + name + ".yml");
  }

  public Configuration getDefault() {
    return new ResourceConfiguration("META-INF/" + name + ".yml");
  }

}
